### ISSUE TITLE
Issues in entry.sh after build and deploy

### ISSUE THREAD

**Issue by tannerCR** [soracom-labs/balena-cellular-AT#1]
@alexissusset Builds fine after changing the base image reference to` balenalib/%%BALENA_MACHINE_NAME%%` in the docker file, however I'm having issues once it is deployed. The log prints the error:

`15.10.19 17:04:36 (-0600) /usr/bin/entry.sh: line 81: tini: command not found`

Then restarts after printing the error twice.

Tried a few quick fixes but to no avail

Running on the Raspberry Pi 4 64x in BalenaOS.

**Comment by alexissusset** [comment]
thank you @tannerCR just pushed an update and everything should be good to go now
